name: Hello World
#Â Make this workflow triggerable manually from the GitHub UI
on: [workflow_dispatch]

jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-667532145122-github-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
